### ISSUE TITLE
ENH: Add ability for containers to automatically stop via JVM shutdown hook - shutdown: stop or shutdown: remove

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test-docker#21]
So we can set shutdownHookMode to be `remove` or `stop` to either stop and remove the container or just stop the container on JVM shutdown.

The intention is that in a CI pipeline it can be preferred to have that behaviour where the container is stopped (& maybe removed).  In the CI build the JVM shutdown should match the end of testing.  This is an alternative to hooking into the maven and gradle build lifecycle.

**Comment by rbygrave** [comment]
Example:  shutdown: remove ... stop and remove the container on JVM shutdown.

```yml
ebean:
  test:
    shutdown: remove
    platform: postgres #, h2, postgres, mysql, oracle, sqlserver
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: test_ex
```

Example:  shutdown: stop ... stop the container only on JVM shutdown.

```yml
ebean:
  test:
    shutdown: stop
    platform: postgres #, h2, postgres, mysql, oracle, sqlserver
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: test_ex
```

Example:  shutdown stop on a specific platform (not all containers).

```yml
ebean:
  test:
    platform: postgres #, h2, postgres, mysql, oracle, sqlserver
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: test_ex
    postgres:
       shutdown: stop
```
