### ISSUE TITLE
ENH: Add support for Redis container

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-test-docker#34]
```yaml
ebean:
  test:
    redis: latest
#    useDocker: false
#    shutdown: stop # stop | remove
    platform: h2 # h2, postgres, mysql, oracle, sqlserver, sqlite
    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
    dbName: myapp
```
